name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not the authors of a pull request have signed the Canonical Contributor Licence Agreement (https://ubuntu.com/legal/contributors).'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
