name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not a particular GitHub user has signed the Canonical Contributor Licence Agreement.'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
