on: [push]

jobs:
  has_signed_cla:
    runs-on: ubuntu-latest
    steps:
      - name: Has Signed Canonical CLA
        uses: MarcusTomlinson/has-signed-canonical-cla@1.0.0
        id: has_signed_cla
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Passed Check
        if: steps.has_signed_cla.outputs.has_signed == 'true'
        run: echo ${{ github.actor }} has signed the Canonical CLA
      - name: Failed Check
        if: steps.has_signed_cla.outputs.has_signed == 'false'
        run: echo ${{ github.actor }} has NOT signed the Canonical CLA
